# AI SCI 210 - Week 1 Thursday

## Function and while-loop warm-up

What is this function doing, and what is its mistake?

In [1]:
def next_even(x):
    y = 0
    while y < x:
        y += 2
    print(y)

In [2]:
next_even(16.57)

18

In [5]:
z

In [3]:
z = next_even(16.57)

18

In [4]:
z + 1

TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

In [7]:
def next_even(x):
    y = 0
    while y < x:
        y += 2
    return y

In [8]:
next_even(16.57)

18

In [9]:
z = next_even(16.57)

## More Python data types

Here are some of the key data types we didn't get to on Tuesday.

## bools

One other very important data type is `bool`.  (We saw this briefly when we asked if `10/2 == 5`, but we didn't focus on the data type.)  The most important thing to know is how it relates to integers.

In [10]:
w = True
type(w)

bool

In [11]:
type(False)

bool

In [12]:
5 is 10/2

<>:1: SyntaxWarning: "is" with 'int' literal. Did you mean "=="?
<>:1: SyntaxWarning: "is" with 'int' literal. Did you mean "=="?
/tmp/ipykernel_6142/2928758045.py:1: SyntaxWarning: "is" with 'int' literal. Did you mean "=="?
  5 is 10/2

False

In [13]:
5.0 is 10/2

<>:1: SyntaxWarning: "is" with 'float' literal. Did you mean "=="?
<>:1: SyntaxWarning: "is" with 'float' literal. Did you mean "=="?
/tmp/ipykernel_6142/3745822545.py:1: SyntaxWarning: "is" with 'float' literal. Did you mean "=="?
  5.0 is 10/2

True

In [15]:
import numpy as np
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Convenient shorthand for counting how many elements in 'arr' are greater than 3.141

In [16]:
arr > 3.141

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [17]:
(arr > 3.131).sum()

np.int64(6)

similar trick for asking what prortion are greater than 3.141. Phrased another way, what's the probability a randomly chosen element in arr is greater than 3.141.

In [18]:
(arr > 3.141).mean()

np.float64(0.6)

## dictionaries

The last built-in Python data type I want to introduce in this portion of the class is the dictionary data type.  Here is an example of constructing a dictionary.  The portions before the colons are called "keys" and the portions after the colons are called "values".  Dictionaries are a favorite data type of many Python users, both new Python users and experienced ones.

In [19]:
d = {"A": 90, "B": 80, "C": 90, "D": 70}

Here is an example of indexing with a dictionary, and of adding new elements to a dictionary.

In [20]:
len(d)

4

In [21]:
d["C"]

90

In [22]:
d["Chris"] = 10

In [23]:
d

{'A': 90, 'B': 80, 'C': 90, 'D': 70, 'Chris': 10}

In [25]:
d["A"] += 3
d

{'A': 96, 'B': 80, 'C': 90, 'D': 70, 'Chris': 10}

In [26]:
d["B"] = 1000
d

{'A': 96, 'B': 1000, 'C': 90, 'D': 70, 'Chris': 10}

In [28]:
d["C"] = [3,1,4,1]
d

{'A': 96, 'B': 1000, 'C': [3, 1, 4, 1], 'D': 70, 'Chris': 10}

Remember that lists were not allowed to go in sets, but tuples were allowed.  It is the same with keys in dictionaries.  (Values in dictionaries can be anything, but there are restrictions on keys; the same restrictions as on elements in sets.)

In [29]:
mylist = [3,1,4,1]
mytuple = (3,1,4,1)

In [30]:
d[mylist] = 10

TypeError: cannot use 'list' as a dict key (unhashable type: 'list')

In [31]:
d[mytuple] = 10
d

{'A': 96, 'B': 1000, 'C': [3, 1, 4, 1], 'D': 70, 'Chris': 10, (3, 1, 4, 1): 10}

## pandas DataFrames

So far we've briefly seen NumPy arrays from the NumPy library.  Here let's briefly see an example of a pandas DataFrame from the pandas library.

In [32]:
import pandas as pd

In [36]:
df = pd.DataFrame({
    "A": [3,1,4,1,5,9],
    "B": [10,1,12,3,4,5]
})

In [34]:
type(df)

pandas.DataFrame

In [37]:
df

   A   B
0  3  10
1  1   1
2  4  12
3  1   3
4  5   4
5  9   5

In [38]:
df.columns

Index(['A', 'B'], dtype='str')

In [39]:
df.index

RangeIndex(start=0, stop=6, step=1)

In [40]:
arr = np.array([[2,3],[2,4],[5,6]])
arr

array([[2, 3],
       [2, 4],
       [5, 6]])

In [41]:
pd.DataFrame(arr)

   0  1
0  2  3
1  2  4
2  5  6

In [48]:
df = pd.DataFrame(arr, columns = ["Chris", "Davis"], index = ["A", "B", "C"])
pd.DataFrame(arr, columns = ["Chris", "Davis"], index = ["A", "B", "C"])

   Chris  Davis
A      2      3
B      2      4
C      5      6

In [47]:
df.loc["B", "Davis"]

np.int64(4)

## Checking for membership

The first homework involves checking for membership in a Python object.  Here is the standard way to do that.

In [49]:
mylist

[3, 1, 4, 1]

In [50]:
4 in mylist

True

## NumPy examples

Here are some examples of constructing certain arrays in NumPy.

## Regular arrays

To learn some different methods for creating NumPy arrays, we will make the following arrays.  (The next one is written as a list, but our primary goal is to make the NumPy array version.)

### Example 1

* [0, 0, 0, ..., 0] (length 10)

In [51]:
np

In [52]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### Example 2

* A five row, seven column matrix containing all 4s.

Here we're trying to make a 5x7 NumPy array of all zeros (then we will add 4 to it).  A common mistake I make is to use `np.zeros(5,7)`.  The error message is not too helpful the first time you see it.

In [ ]:
np.zeros(5, 7) + 4

TypeError: Cannot interpret '7' as a data type

In [54]:
help(np.zeros)

Help on built-in function zeros in module numpy:

zeros(shape, dtype=None, order='C', *, device=None, like=None)
    zeros(shape, dtype=None, order='C', *, device=None, like=None)

    Return a new array of given shape and type, filled with zeros.

    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in memory.
    device : str, optional
        The device on which to place the created array. Default: ``None``.
        For Array-API interoperability only, so must be ``"cpu"`` if passed.

        .. versionadded:: 2.0.0
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.

        .. versionadded:: 1.20.0

    Returns
    -------
    out : ndarray
        Array of zeros with the given shape, dtype, and order.

    See Also
    --------
    zeros_like : Return an array of zeros with shape and type of input.
    empty : Return a new uninitialized array.
    ones : Return a new array setting values to one.
    full : Return a new array of given shape filled with value.

    Examples
    --------
    >>> import numpy as np
    >>> np.zeros(5)
    array([ 0.,  0.,  0.,  0.,  0.])

    >>> np.zeros((5,), dtype=np.int_)
    array([0, 0, 0, 0, 0])

    >>> np.zeros((2, 1))
    array([[ 0.],
           [ 0.]])

    >>> s = (2,2)
    >>> np.zeros(s)
    array([[ 0.,  0.],
           [ 0.,  0.]])

    >>> np.zeros((2,), dtype=[('x', 'i4'), ('y', 'i4')]) # custom dtype
    array([(0, 0), (0, 0)],
          dtype=[('x', '<i4'), ('y', '<i4')])

In [55]:
np.zeros((5, 7)) + 4

array([[4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4.]])

In [56]:
np.zeros(shape = [5, 7], dtype = int) + 4

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

Here is another straegy using the full funcation

In [57]:
np.full(shape = [5, 7], fill_value = 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

If we would rather have integers on the inside (notice how the decimal point goes away), we can specify `int` as the `dtype`.

Here is another strategy, using the `full` function (which I did not know about when I wrote the other strategy).

### Example 3

* [0, ..., 5] (length 100, evenly distributed).

This type of array is often used in plotting, for example, if we know how many sample points we want to plot in the interval.

In [58]:
np.linspace(0, 5, 100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737374,
       3.78787879, 3.83838384, 3.88888889, 3.93939394, 3.98989899,
       4.04040404, 4.09090909, 4.14141414, 4.19191919, 4.24242424,
       4.29292929, 4.34343434, 4.39393939, 4.44444444, 4.49494949,
       4.54545455, 4.5959596 , 4.64646465, 4.6969697 , 4.74747475,
       4.7979798 , 4.84848485, 4.8989899 , 4.94949495, 5.        ])

### Example 3.5

* [0, 0.01, 0.02, ..., 4.99]

In [59]:
np.arange(0, 5, 0.01)

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
       0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
       0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
       0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
       0.99, 1.  , 1.01, 1.02, 1.03, 1.04, 1.05, 1.06, 1.07, 1.08, 1.09,
       1.1 , 1.11, 1.12, 1.13, 1.14, 1.15, 1.16, 1.17, 1.18, 1.19, 1.2 ,
       1.21, 1.22, 1.23, 1.24, 1.25, 1.26, 1.27, 1.28, 1.29, 1.3 , 1.31,
       1.32, 1.33, 1.34, 1.35, 1.36, 1.37, 1.38, 1.39, 1.4 , 1.41, 1.42,
       1.43, 1.44, 1.45, 1.46, 1.47, 1.48, 1.49, 1.5 , 1.51, 1.52, 1.53,
       1.54, 1.55, 1.56, 1.57, 1.58, 1.59, 1.6 , 1.61, 1.62, 1.63, 1.64,
       1.65, 1.66, 1.67, 1.68, 1.69, 1.7 , 1.71, 1.72, 1.73, 1.74, 1.75,
       1.76, 1.77, 1.78, 1.79, 1.8 , 1.81, 1.82, 1.83, 1.84, 1.85, 1.86,
       1.87, 1.88, 1.89, 1.9 , 1.91, 1.92, 1.93, 1.94, 1.95, 1.96, 1.97,
       1.98, 1.99, 2.  , 2.01, 2.02, 2.03, 2.04, 2.05, 2.06, 2.07, 2.08,
       2.09, 2.1 , 2.11, 2.12, 2.13, 2.14, 2.15, 2.16, 2.17, 2.18, 2.19,
       2.2 , 2.21, 2.22, 2.23, 2.24, 2.25, 2.26, 2.27, 2.28, 2.29, 2.3 ,
       2.31, 2.32, 2.33, 2.34, 2.35, 2.36, 2.37, 2.38, 2.39, 2.4 , 2.41,
       2.42, 2.43, 2.44, 2.45, 2.46, 2.47, 2.48, 2.49, 2.5 , 2.51, 2.52,
       2.53, 2.54, 2.55, 2.56, 2.57, 2.58, 2.59, 2.6 , 2.61, 2.62, 2.63,
       2.64, 2.65, 2.66, 2.67, 2.68, 2.69, 2.7 , 2.71, 2.72, 2.73, 2.74,
       2.75, 2.76, 2.77, 2.78, 2.79, 2.8 , 2.81, 2.82, 2.83, 2.84, 2.85,
       2.86, 2.87, 2.88, 2.89, 2.9 , 2.91, 2.92, 2.93, 2.94, 2.95, 2.96,
       2.97, 2.98, 2.99, 3.  , 3.01, 3.02, 3.03, 3.04, 3.05, 3.06, 3.07,
       3.08, 3.09, 3.1 , 3.11, 3.12, 3.13, 3.14, 3.15, 3.16, 3.17, 3.18,
       3.19, 3.2 , 3.21, 3.22, 3.23, 3.24, 3.25, 3.26, 3.27, 3.28, 3.29,
       3.3 , 3.31, 3.32, 3.33, 3.34, 3.35, 3.36, 3.37, 3.38, 3.39, 3.4 ,
       3.41, 3.42, 3.43, 3.44, 3.45, 3.46, 3.47, 3.48, 3.49, 3.5 , 3.51,
       3.52, 3.53, 3.54, 3.55, 3.56, 3.57, 3.58, 3.59, 3.6 , 3.61, 3.62,
       3.63, 3.64, 3.65, 3.66, 3.67, 3.68, 3.69, 3.7 , 3.71, 3.72, 3.73,
       3.74, 3.75, 3.76, 3.77, 3.78, 3.79, 3.8 , 3.81, 3.82, 3.83, 3.84,
       3.85, 3.86, 3.87, 3.88, 3.89, 3.9 , 3.91, 3.92, 3.93, 3.94, 3.95,
       3.96, 3.97, 3.98, 3.99, 4.  , 4.01, 4.02, 4.03, 4.04, 4.05, 4.06,
       4.07, 4.08, 4.09, 4.1 , 4.11, 4.12, 4.13, 4.14, 4.15, 4.16, 4.17,
       4.18, 4.19, 4.2 , 4.21, 4.22, 4.23, 4.24, 4.25, 4.26, 4.27, 4.28,
       4.29, 4.3 , 4.31, 4.32, 4.33, 4.34, 4.35, 4.36, 4.37, 4.38, 4.39,
       4.4 , 4.41, 4.42, 4.43, 4.44, 4.45, 4.46, 4.47, 4.48, 4.49, 4.5 ,
       4.51, 4.52, 4.53, 4.54, 4.55, 4.56, 4.57, 4.58, 4.59, 4.6 , 4.61,
       4.62, 4.63, 4.64, 4.65, 4.66, 4.67, 4.68, 4.69, 4.7 , 4.71, 4.72,
       4.73, 4.74, 4.75, 4.76, 4.77, 4.78, 4.79, 4.8 , 4.81, 4.82, 4.83,
       4.84, 4.85, 4.86, 4.87, 4.88, 4.89, 4.9 , 4.91, 4.92, 4.93, 4.94,
       4.95, 4.96, 4.97, 4.98, 4.99])

In [60]:
range(0, 5, 2)

range(0, 5, 2)

### Example 4

* The 3x3 matrix $\begin{pmatrix} 0 & 0 & 0 \\ 1 & 1 & 1 \\ 2 & 2 & 2 \end{pmatrix}$

In [62]:
arr = np.zeros(shape = [3, 3])

for i in range(3):
    arr[i] = i

In [63]:
arr

array([[0., 0., 0.],
       [1., 1., 1.],
       [2., 2., 2.]])

Here is a first way to make this matrix.  It's again using broadcasting.  For example, when `i` is 2, we broadcast 2 to the second row.  (The second row is specified by `arr[2]`.)  We will later see ways to make this sort of matrix avoiding the for loop.

## Plots of timings

Let's see visually how search speeds can differ.

Here we consider searching for an element that occurs near the end of a list.

In [64]:
%%timeit
1 in mylist

26.9 ns ± 2.05 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)

In [65]:
import time

In [69]:
start = time.perf_counter()
1 in mylist
elapsed = time.perf_counter() - start
print(elapsed)

0.00015557100050500594

Here we consider getting the value associated to a certain key in a dictionary.

## Random numbers

In a normal distribution, we expect approximately 95.44% of samples to lie within two standard deviations of the mean.  Perform an experiment and see how closely the experiment matches that estimate.  Use a seed to have reproducible results.